[package]
name = "othello_game"
version.workspace = true
edition.workspace = true

[dependencies]
rand.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "bench_board"
harness = false
